name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '0 21 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
            scala: 2.12.8
          - java: 8
            scala: 2.12.8
          - java: 11
            scala: 2.10.7
          - java: 8
            scala: 2.10.7
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - uses: coursier/cache-action@v5
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        shell: bash
        run: |
          mkdir ~/.sbt || true && echo "
          accessKey = $AWS_ACCESS_KEY_ID
          secretKey = $AWS_SECRET_KEY
          " >> ~/.sbt/.s3credentials_maven.custom
      - name: Build and test
        run: |
          sbt -v \
            $(if [[ "${{matrix.scala}}" == 2\.10* ]] ; \
              then \
                echo "++${{matrix.scala}} ^^0.13.18 clean test publishLocal scripted" ; \
              else \
                echo "++${{matrix.scala}} clean test publishLocal
                  ^^1.1.6 scripted
                  ^^1.2.8 scripted
                  ^^1.3.13 scripted
                  ^^1.4.9 scripted
                  ^^1.5.5 scripted" ; \
            fi)
          rm -rf "$HOME/.ivy2/local" || true
          rm -rf "$HOME/.ivy2/cache/com.eed3si9n" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt
